name: Release

on:
  workflow_run:
    workflows: [ "Wheels" ]
    branches: [ next ]
    types: 
      - completed
  push:
    branches: [ next ]

jobs:
  a:
    name: a
    runs-on: ubuntu-latest
    steps:
      - run: echo ok
  publish-to-testpypi:
    name: Publish Python 🐍 distribution 📦 to TestPyPI
    needs:
      - wheels-apple
      - wheels-linux
    # if: startsWith(github.ref, 'refs/tags/')  # only publish to PyPI on tag pushes
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/wtr-watcher-runner
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
    steps:
      - run: |
          tool/fetch-release-artifacts --no-zip
          mkdir dist
          find out/dist -name '*.whl' | while read f
          do cp "$f" dist ; echo "$f"
          done
      - name: Publish distribution 📦 to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
