name: Dist

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  linux-dist:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        triple:
          - aarch64-unknown-linux-gnu
          - aarch64-unknown-linux-musl 
          - armv7-unknown-linux-gnueabihf
          - armv7-unknown-linux-musleabihf
          - x86_64-unknown-linux-gnu
          - x86_64-unknown-linux-musl
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - shell: bash
        run: tool/cross --target-${{matrix.triple}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.triple}}.tar
          path: out/${{matrix.triple}}.tar
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.triple}}.tar.sha256sum
          path: out/${{matrix.triple}}.tar.sha256sum
  apple-dist:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - macos-latest
        triple:
          - aarch64-apple-darwin
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - shell: bash
        run: tool/cross --target-${{matrix.triple}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.triple}}.tar
          path: out/${{matrix.triple}}.tar
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.triple}}.tar.sha256sum
          path: out/${{matrix.triple}}.tar.sha256sum
  windows-dist:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - windows-latest
        triple:
          - x86_64-pc-windows-msvc
          - aarch64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - shell: bash
        run: tool/cross --target-${{matrix.triple}}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.triple}}.tar
          path: out/${{matrix.triple}}.tar
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.triple}}.tar.sha256sum
          path: out/${{matrix.triple}}.tar.sha256sum
