name: macOS

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    permissions:
      id-token: write
      contents: read
      attestations: write
    strategy:
      fail-fast: false
      matrix:
        target-double:
          - apple-darwin
        target-platform:
          - this
        os:
          - macos-13
          - macos-14
    steps:
      - uses: lukka/get-cmake@v3.29.3
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: out
          key: cache.${{matrix.target-double}}.${{matrix.os}}
      - uses: chetan/git-restore-mtime-action@v2
      - run: tool/build --verbose --no-run
      - run: tool/test/all
      - run: tool/build --verbose --no-build --no-run-perf
      - run: tool/build --verbose --no-build --no-run-unit
      - run: ls -al out/${{matrix.target-platform}}/Debug
      - run: ls -al out/${{matrix.target-platform}}/Release
