name: Windows

on:
  push:
    branches: [ release, next ]
  pull_request:
    branches: [ release, next ]

jobs:
  build:
    runs-on: ${{matrix.os}}
    permissions:
      id-token: write
      contents: read
      attestations: write
    strategy:
      matrix:
        target-double:
          - uwp-windows-msvc
        target-platform:
          - this
        os:
          - windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/cache@v4
        with:
          path: out
          key: cache.${{matrix.target-double}}.${{matrix.os}}
      - uses: chetan/git-restore-mtime-action@v2
      - uses: aminya/setup-cpp@v1
        with:
          compiler: 'msvc'
          vcvarsall: true
          cmake: true
          ccache: false
          ninja: false
          conan: false
          vcpkg: false
          gcovr: false
          cppcheck: false
          clangtidy: false
          opencppcoverage: false
      - run: |
          cl.exe src/wtr/tiny_watcher/main.cpp /Iinclude /std:c++17 /O2 /EHs /EHr /EHc /Fe:tiny.exe
          bash -c 'ls -hal tiny.exe'
      - shell: bash
        run: |
          cmake -S . -B out/${{matrix.target-platform}}
          cmake --build out/${{matrix.target-platform}} --target wtr.test_watcher --config Debug
          cmake --build out/${{matrix.target-platform}} --target wtr.test_watcher --config Release
      - shell: bash
        env:
          VERBOSE: 1
        run: |
          out/${{matrix.target-double}}/Debug/wtr.test_watcher.exe || echo f windows
          out/${{matrix.target-double}}/Release/wtr.test_watcher.exe || echo f windows
      - run: echo windows is an abomination
